SELECT FI.ID, FIN.FISH_NAME, FI.LENGTH
FROM FISH_NAME_INFO AS FIN 
INNER JOIN FISH_INFO AS FI
ON FIN.FISH_TYPE = FI.FISH_TYPE 
WHERE (FI.FISH_TYPE, FI.LENGTH) IN
(
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY FI.ID